/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    assets: Asset;
    sale_events: SaleEvent;
    services: Service;
    testimonials: Testimonial;
    site_stats: SiteStat;
    inquiries: Inquiry;
    orders: Order;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    assets: AssetsSelect<false> | AssetsSelect<true>;
    sale_events: SaleEventsSelect<false> | SaleEventsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    site_stats: SiteStatsSelect<false> | SiteStatsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    delivery: Delivery;
  };
  globalsSelect: {
    delivery: DeliverySelect<false> | DeliverySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Leave blank to generate from the title.
   */
  slug: string;
  description?: string | null;
  division: 'estate_sales' | 'commercial_liquidation' | 'concierge' | 'expat_services';
  category:
    | 'furniture'
    | 'fine_art'
    | 'jewelry'
    | 'vehicles'
    | 'collectibles'
    | 'designer'
    | 'lighting'
    | 'rugs'
    | 'antiques'
    | 'equipment'
    | 'fleet'
    | 'inventory'
    | 'office'
    | 'other';
  /**
   * Type the specific category — shown on the site instead of "Other".
   */
  category_other?: string | null;
  status: 'available' | 'reserved' | 'pending' | 'sold' | 'withdrawn';
  condition?: ('new' | 'excellent' | 'very_good' | 'good' | 'fair') | null;
  price?: number | null;
  currency?: string | null;
  price_on_request?: boolean | null;
  brand?: string | null;
  era?: string | null;
  provenance?: string | null;
  dimensions?: string | null;
  location?: string | null;
  /**
   * Array of tag strings, e.g. ["mid-century", "teak"].
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Free-form JSON consumed by the site (e.g. { "meta": "...", "tone": "navy" }).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Ordered gallery. Tick "Use as thumbnail" on one image to set the cover; otherwise the first image is used. A single image is automatically the thumbnail. Saving rebuilds the public image URLs.
   */
  images?:
    | {
        image: string | Media;
        is_cover?: boolean | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  is_featured?: boolean | null;
  sort_order?: number | null;
  /**
   * Auto-filled from the first gallery image.
   */
  primary_image_url?: string | null;
  /**
   * Auto-built [{url, alt}] read by the public site.
   */
  gallery?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt?: string | null;
  /**
   * Optional photographer / source credit.
   */
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sale_events".
 */
export interface SaleEvent {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Leave blank to generate from the title.
   */
  slug: string;
  description?: string | null;
  event_type: 'estate_sale' | 'online_auction' | 'liquidation' | 'private_event';
  status: 'upcoming' | 'live' | 'ended' | 'cancelled';
  division: 'estate_sales' | 'commercial_liquidation' | 'concierge' | 'expat_services';
  /**
   * Neighbourhood / city
   */
  location?: string | null;
  address?: string | null;
  starts_at?: string | null;
  ends_at?: string | null;
  /**
   * Public image URL for the event cover.
   */
  cover_image_url?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  is_featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * URL-safe identifier. Leave blank to generate from the title.
   */
  slug: string;
  division: 'estate_sales' | 'commercial_liquidation' | 'concierge' | 'expat_services';
  summary?: string | null;
  description?: string | null;
  /**
   * Icon key used by the site UI.
   */
  icon?: ('estate' | 'commercial' | 'concierge') | null;
  /**
   * Array of bullet strings, e.g. ["Inventory & cataloguing", ...].
   */
  offerings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Public image URL for the service hero.
   */
  hero_image_url?: string | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  author_name: string;
  author_role?: string | null;
  quote: string;
  client_segment?:
    | ('individual' | 'family' | 'estate_executor' | 'business_owner' | 'expat' | 'embassy' | 'corporation')
    | null;
  location?: string | null;
  rating?: number | null;
  /**
   * Public image URL for the author avatar.
   */
  avatar_url?: string | null;
  is_featured?: boolean | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_stats".
 */
export interface SiteStat {
  id: string;
  /**
   * Stable key, e.g. 'assets_sold'.
   */
  key: string;
  label: string;
  value: number;
  /**
   * e.g. 'KES '
   */
  prefix?: string | null;
  /**
   * e.g. '+', 'B', '%'
   */
  suffix?: string | null;
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  /**
   * Pipeline stage.
   */
  status: 'new' | 'contacted' | 'qualified' | 'won' | 'lost' | 'archived';
  inquiry_type: 'consultation' | 'asset_review';
  full_name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  preferred_contact?: string | null;
  client_segment?:
    | ('individual' | 'family' | 'estate_executor' | 'business_owner' | 'expat' | 'embassy' | 'corporation')
    | null;
  service_division?: ('estate_sales' | 'commercial_liquidation' | 'concierge' | 'expat_services') | null;
  location?: string | null;
  expat_direction?: string | null;
  subject?: string | null;
  message?: string | null;
  asset_category?:
    | (
        | 'furniture'
        | 'fine_art'
        | 'jewelry'
        | 'vehicles'
        | 'collectibles'
        | 'designer'
        | 'lighting'
        | 'rugs'
        | 'antiques'
        | 'equipment'
        | 'fleet'
        | 'inventory'
        | 'office'
        | 'other'
      )
    | null;
  asset_description?: string | null;
  estimated_value?: number | null;
  estimated_currency?: string | null;
  /**
   * Privacy/contact consent given on submission.
   */
  consent?: boolean | null;
  /**
   * Page / CTA the lead came from.
   */
  source?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Auto-generated (EE-XXXXXX).
   */
  order_number?: string | null;
  /**
   * Fulfilment stage.
   */
  status: 'pending' | 'confirmed' | 'dispatched' | 'delivered' | 'cancelled';
  full_name: string;
  phone: string;
  email?: string | null;
  /**
   * Used to price delivery.
   */
  county?: string | null;
  town?: string | null;
  address?: string | null;
  delivery_notes?: string | null;
  /**
   * Cart lines: [{ title, slug, price, quantity, image_url }]. Written at checkout.
   */
  items?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Sum of item lines.
   */
  subtotal?: number | null;
  /**
   * Countrywide delivery charge.
   */
  delivery_fee?: number | null;
  /**
   * subtotal + delivery.
   */
  total?: number | null;
  currency?: string | null;
  /**
   * Derived from payments below.
   */
  payment_status?: ('unpaid' | 'partial' | 'paid') | null;
  amount_paid?: number | null;
  /**
   * Record each payment received after delivery. Updates amount paid + status.
   */
  payments?:
    | {
        amount: number;
        method?: ('pay_on_delivery' | 'mpesa' | 'cash' | 'bank_transfer') | null;
        paid_at?: string | null;
        /**
         * M-Pesa code / receipt no.
         */
        reference?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When fully paid.
   */
  paid_at?: string | null;
  /**
   * Page / CTA the order came from.
   */
  source?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  /**
   * Admins manage users and everything else. Editors manage content + inquiries.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'sale_events';
        value: string | SaleEvent;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'site_stats';
        value: string | SiteStat;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  division?: T;
  category?: T;
  category_other?: T;
  status?: T;
  condition?: T;
  price?: T;
  currency?: T;
  price_on_request?: T;
  brand?: T;
  era?: T;
  provenance?: T;
  dimensions?: T;
  location?: T;
  tags?: T;
  metadata?: T;
  images?:
    | T
    | {
        image?: T;
        is_cover?: T;
        alt?: T;
        id?: T;
      };
  is_featured?: T;
  sort_order?: T;
  primary_image_url?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sale_events_select".
 */
export interface SaleEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  event_type?: T;
  status?: T;
  division?: T;
  location?: T;
  address?: T;
  starts_at?: T;
  ends_at?: T;
  cover_image_url?: T;
  metadata?: T;
  is_featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  division?: T;
  summary?: T;
  description?: T;
  icon?: T;
  offerings?: T;
  hero_image_url?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author_name?: T;
  author_role?: T;
  quote?: T;
  client_segment?: T;
  location?: T;
  rating?: T;
  avatar_url?: T;
  is_featured?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_stats_select".
 */
export interface SiteStatsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  prefix?: T;
  suffix?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  inquiry_type?: T;
  full_name?: T;
  email?: T;
  phone?: T;
  company?: T;
  preferred_contact?: T;
  client_segment?: T;
  service_division?: T;
  location?: T;
  expat_direction?: T;
  subject?: T;
  message?: T;
  asset_category?: T;
  asset_description?: T;
  estimated_value?: T;
  estimated_currency?: T;
  consent?: T;
  source?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  order_number?: T;
  status?: T;
  full_name?: T;
  phone?: T;
  email?: T;
  county?: T;
  town?: T;
  address?: T;
  delivery_notes?: T;
  items?: T;
  subtotal?: T;
  delivery_fee?: T;
  total?: T;
  currency?: T;
  payment_status?: T;
  amount_paid?: T;
  payments?:
    | T
    | {
        amount?: T;
        method?: T;
        paid_at?: T;
        reference?: T;
        note?: T;
        id?: T;
      };
  paid_at?: T;
  source?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery".
 */
export interface Delivery {
  id: string;
  enabled?: boolean | null;
  /**
   * Short line shown on product cards, detail pages and checkout.
   */
  message?: string | null;
  /**
   * Longer explanation shown on the Delivery & Returns section.
   */
  details?: string | null;
  /**
   * Default countrywide fee (KES) when no county rate matches.
   */
  flat_fee?: number | null;
  /**
   * Order subtotal (KES) at/above which delivery is free. Leave blank to disable.
   */
  free_above?: number | null;
  /**
   * Optional overrides, e.g. { "Nairobi": 300, "Mombasa": 800 }. Falls back to the flat fee.
   */
  county_rates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery_select".
 */
export interface DeliverySelect<T extends boolean = true> {
  enabled?: T;
  message?: T;
  details?: T;
  flat_fee?: T;
  free_above?: T;
  county_rates?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}